### ISSUE TITLE
Scaffold Module and Components for Data & Analytics

### ISSUE THREAD

**Issue by ghost** [TAMULib/scholars-angular#231]

**Comment by wwelling** [comment]
Define route structure, please.

**Comment by wwelling** [comment]
`/data-analytics`


![Image](https://github.com/TAMULib/scholars-angular/assets/8352733/833a3b44-932a-4579-9365-6d719326ff5c)

**Comment by wwelling** [comment]
`/data-analytics/Publications by Academic Age Group`

![Image](https://github.com/TAMULib/scholars-angular/assets/8352733/b439a6fa-7849-456f-8b2c-260877d33fe9)

**Comment by wwelling** [comment]
Next steps

- [ ] add app setting for initial organization id
- [ ] apply organization id at appropriate labels (breadcrumbs, navigations, wherever branding needs organization data)
- [ ] refactor visualization components to support lazily providing id *ensure still works in visualization route context as will be useful to provide at a display view
