### ISSUE TITLE
In Discovery view: Search bar does not match entity type

### ISSUE THREAD

**Issue by C2H5-M** [TAMULib/scholars-angular#396]
In Discovery view:
1. Select Concepts tab  
2. search bar is "Search Concepts..."
3. Click any concept 
4. Search bar is now "Search Awards..."
So far, I've only seen this in Concepts.  When you do a search in this page, it produces search results from Awards, not Concepts.
Proposed possible solution: Ensure search bar and function matches the entity type displayed/browsed
![Image](https://github.com/user-attachments/assets/b121e64e-1d9c-4fdb-abb7-a18e36dc09c7)

**Comment by Dbreck-TAMU** [comment]
src\app\core\store\sdr\index.ts

const findCollectionView
