### ISSUE TITLE
Publisher and External Organizations types: Remove Temporal Graphs and Maps of Science links

### ISSUE THREAD

**Issue by C2H5-M** [TAMULib/scholars-angular#399]
Is it possible to remove the Temporal Graphs and Maps of Science links for external organizations and publisher type entities?  These are "dead" links - does not create any graphs.
![Image](https://github.com/user-attachments/assets/f5135a20-0d06-4c62-863c-cc7075e98b4f)
![Image](https://github.com/user-attachments/assets/f701ebf4-7af7-4371-b90c-cf24e75ea3cd)

![Image](https://github.com/user-attachments/assets/870def09-ce51-4548-aeb5-ee16f4a66ac7)
![Image](https://github.com/user-attachments/assets/a213c0e6-de88-49f4-b449-bc7b8306f72c)

**Comment by Dbreck-TAMU** [comment]
Due to the time constraints, this was a 'quick fix'. For a long term solution we will want to update the data to tell the UI if a sidebar should be shown or not.
