### ISSUE TITLE
Add search tips under search window in discovery view

### ISSUE THREAD

**Issue by ghost** [TAMULib/scholars-angular#64]
1. Type keywords using AND or OR logic (AND or OR must be capitalized)
  e.g., nutrition AND protein
2. Type your phrase with double quotation marks
  e.g., "glucose absorption" OR nutrition
3. Use wildcard * character to search variations
  e.g., bio*

![image](https://user-images.githubusercontent.com/8352733/157678293-02c10f7d-a0d8-414f-b5ce-898e32983973.png)

**Comment by artjynx** [comment]
Will this be an update to the current search tips? My initial thought for the tips would be a modal versus a separate page. See attached. I'm trying to be more specific with the design choices in comps for developers. If you have consistent colors you're using for buttons, and radius for modals and such please keep with your standard.  Please let me know if this is doable.
![searchtip_modal](https://user-images.githubusercontent.com/4729076/158192516-843cec7f-cda0-403b-8745-6827c45bc639.jpg)

**Comment by artjynx** [comment]
I haven't shown this to DJ yet. I wanted to make sure there weren't issues on your end first.

**Comment by artjynx** [comment]
Hi William - 
DJ approved small tweaks to the links below the input fields. 

basically switching the order of the links and adding an inline icon to the search tips.
The icon is a bootstrap icon - https://icons.getbootstrap.com/icons/info-circle-fill/

The color of the yellow is from the a&m brand guide -# FCE300
The hover state can stay white as is...
Please let me know if you have questions

![scholars_front](https://user-images.githubusercontent.com/4729076/158444370-086d5ceb-76c5-4ef8-943a-b3fe955c2cd0.jpg)
![scholars search_tips](https://user-images.githubusercontent.com/4729076/158444404-2f87e75b-7b6e-46d7-8342-8f2d0da2829e.jpg)
